 services:
    db:
       image: mysql:8
       environment:
         MYSQL_ROOT_PASSWORD: root
         MYSQL_DATABASE: challenge
       ports:
         - 3306:3306
       volumes:
         - ./.docker/mysql:/docker-entrypoint-initdb.d