USE [challenge]
GO

CREATE TABLE Account (
    AccountId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    PersonId UNIQUEIDENTIFIER NOT NULL,
    AccountNumber NVARCHAR(20) UNIQUE NOT NULL,
    Balance DECIMAL(10,2) DEFAULT 0.00,
    CreatedAt DATETIME DEFAULT GETDATE(),
    UpdatedAt DATETIME NULL,
    FOREIGN KEY (PersonId) REFERENCES Person(PersonId) ON DELETE CASCADE
)
GO