USE [challenge]
GO

CREATE TABLE Deposit (
    DepositId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    PersonId UNIQUEIDENTIFIER NOT NULL,
    AccountNumber VARCHAR(8) NOT NULL,
    Value DECIMAL(10,2) DEFAULT 0.00,
    CreatedAt DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (PersonId) REFERENCES Person(PersonId) ON DELETE CASCADE
)
GO