USE [challenge]
GO

CREATE TABLE EmailTemplate (
    EmailTemplateId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Subject VARCHAR(100) NOT NULL,
    Body VARCHAR(3000) NOT NULL,
    Type VARCHAR(20) UNIQUE NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE() NOT NULL
)
GO