USE [challenge]
GO

CREATE TABLE IndividualPerson (
    IndividualPersonId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    PersonId UNIQUEIDENTIFIER NOT NULL,
    CPF VARCHAR(11) UNIQUE NOT NULL,
    BirthDate DATETIME NOT NULL,
    FOREIGN KEY (PersonId) REFERENCES Person(PersonId) ON DELETE CASCADE
)
GO