USE [challenge]
GO

CREATE TABLE [Token] (
    TokenId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Token VARCHAR(1200) NOT NULL,
    Expiration DATETIME NOT NULL,
    UserId UNIQUEIDENTIFIER NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE()
)
GO