USE [challenge]
GO

CREATE TABLE [Transfer] (
    TransferId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    PayerId UNIQUEIDENTIFIER NOT NULL,
    PayeeId UNIQUEIDENTIFIER NOT NULL,
    Value DECIMAL(10,2) NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE()
)
GO